  /api/calendars/:
    get:
      summary: List calendars
      operationId: get_api_calendars_
      responses:
        '200':
          description: Available church calendar identifiers
          content:
            application/json:
              schema:
                type: object
                properties:
                  calendars:
                    type: array
                    items:
                      type: string
