# Generated by Django 4.2.23 on 2025-07-21 02:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Biography",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512)),
                ("religion", models.CharField(max_length=64)),
                ("calendar", models.CharField(max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HagiographyCitationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("citation", models.TextField()),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "date_accessed",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Saint",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "month",
                    models.IntegerField(
                        help_text="Month the saint is commemorated on the calendar as an integer from 1 to 12"
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        help_text="Day of the month the saint is commemorated on the calendar as an integer from 1 to 31"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the saint", max_length=512),
                ),
                (
                    "canonization_status",
                    models.CharField(
                        blank=True,
                        help_text="Title of the saint, such as Saint (St), Saints (SS), Blessed (Bd), Blesseds (BB), Venerable, etc.",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Category or categories of the saint such as Martyr, Confessor, Virgin, King, Queen, Penitent, Bishop, Archbishop, etc.",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "biography_or_hagiography",
                    models.TextField(help_text="Biography or Hagiography of the saint"),
                ),
                (
                    "footnotes",
                    models.TextField(
                        blank=True,
                        help_text="Footnotes to the biography of the saint, if provided",
                        null=True,
                    ),
                ),
                (
                    "reflection",
                    models.TextField(
                        blank=True,
                        help_text="A reflection or meditation on the life of the saint, if provided",
                        null=True,
                    ),
                ),
                (
                    "volume",
                    models.IntegerField(
                        blank=True,
                        help_text="Volume number of the book, from 1 to 4",
                        null=True,
                    ),
                ),
                (
                    "page_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Page number of the book, from 1 to 3000",
                        null=True,
                    ),
                ),
                (
                    "year_of_death",
                    models.CharField(
                        blank=True,
                        help_text="Year of death often in the format 'A.D. 700', but can also be more generic such as 'Seventh Century' or a range",
                        max_length=512,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WritingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("writing", models.TextField()),
                ("date", models.CharField(max_length=128)),
                ("title", models.CharField(max_length=256)),
                ("url", models.URLField(blank=True, null=True)),
                ("author", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("by", "By Saint"), ("about", "About Saint")],
                        max_length=32,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "biography",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writings",
                        to="saints.biography",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TraditionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tradition", models.TextField()),
                (
                    "country_of_origin",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "reason_associated_with_saint",
                    models.TextField(blank=True, null=True),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "biography",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traditions",
                        to="saints.biography",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShortDescriptionsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("one_sentence_description", models.TextField()),
                ("one_paragraph_description", models.TextField()),
                (
                    "biography",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_descriptions",
                        to="saints.biography",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuoteModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("person", models.CharField(max_length=256)),
                ("date", models.CharField(max_length=128)),
                (
                    "biography",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote",
                        to="saints.biography",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegendModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legend", models.TextField()),
                ("title", models.CharField(max_length=256)),
                (
                    "biography",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legend",
                        to="saints.biography",
                    ),
                ),
                (
                    "citations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="legends",
                        to="saints.hagiographycitationmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=256)),
                ("author", models.CharField(blank=True, max_length=256, null=True)),
                ("date", models.CharField(blank=True, max_length=128, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "biography",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="saints.biography",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HagiographyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hagiography", models.TextField()),
                (
                    "biography",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hagiography",
                        to="saints.biography",
                    ),
                ),
                (
                    "citations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="hagiographies",
                        to="saints.hagiographycitationmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_name", models.CharField(max_length=128)),
                ("description", models.TextField()),
                (
                    "country_of_origin",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "reason_associated_with_saint",
                    models.TextField(blank=True, null=True),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "biography",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foods",
                        to="saints.biography",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeastDescriptionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feast_description", models.TextField()),
                (
                    "biography",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feast_description",
                        to="saints.biography",
                    ),
                ),
                (
                    "citations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="feast_descriptions",
                        to="saints.hagiographycitationmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("month", models.PositiveSmallIntegerField()),
                ("day", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("latin_name", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "english_name",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "english_translation",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("color", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "latin_notes",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "english_notes",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_primary_for_day", models.BooleanField(default=False)),
                (
                    "temporale_or_sanctorale",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("latin_rank", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "english_rank",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_person", models.BooleanField(default=False)),
                ("saint_name", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "saint_category",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("saint_categories", models.JSONField(blank=True, null=True)),
                (
                    "saint_singular_or_plural",
                    models.CharField(
                        blank=True,
                        choices=[("singular", "Singular"), ("plural", "Plural")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("calendar", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "subcalendar",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("season", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "biography",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_events",
                        to="saints.biography",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BulletPointsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "biography",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullet_points",
                        to="saints.biography",
                    ),
                ),
                (
                    "citations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bullet_points",
                        to="saints.hagiographycitationmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BulletPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "bullet_points_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullet_points",
                        to="saints.bulletpointsmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BibleVerseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("citation", models.CharField(max_length=256)),
                ("text", models.TextField()),
                ("bible_version_abbreviation", models.CharField(max_length=32)),
                ("bible_version", models.CharField(max_length=128)),
                ("bible_version_year", models.CharField(max_length=8)),
                (
                    "biography",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_verse",
                        to="saints.biography",
                    ),
                ),
            ],
        ),
    ]
