# Generated by Django 4.2.21 on 2025-07-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saints", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="slug",
            field=models.SlugField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="podcastepisode",
            name="slug",
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
