# Generated by Django 4.2.21 on 2025-08-24 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("saints", "0004_playback_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="podcastlistenlog",
            new_name="saints_podc_created_15c443_idx",
            old_name="saints_podcastlisten_created_idx",
        ),
        migrations.RenameIndex(
            model_name="podcastlistenlog",
            new_name="saints_podc_podcast_eb7132_idx",
            old_name="saints_podcastlisten_pod_ep_idx",
        ),
        migrations.RenameIndex(
            model_name="podcastlistenlog",
            new_name="saints_podc_ip_addr_977c91_idx",
            old_name="saints_podcastlisten_ip_idx",
        ),
        migrations.RenameIndex(
            model_name="podcastlistenlog",
            new_name="saints_podc_fingerp_ba4dfb_idx",
            old_name="saints_podcastlisten_fp_idx",
        ),
        migrations.RenameIndex(
            model_name="podcastlistenlog",
            new_name="saints_podc_playbac_1f8c2b_idx",
            old_name="saints_podcastlisten_playback_idx",
        ),
        migrations.AlterField(
            model_name="podcastlistenlog",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
